name: mfunction_raw
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  equatable: ^2.0.5
  math_expressions: ^2.4.0
  equations: ^5.0.2
  console: ^4.1.0
  bloc: ^8.1.3
  hive: ^2.2.3
  meta: ^1.12.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
